### ISSUE TITLE
Censor all secure fields from being logged

### ISSUE THREAD

**Issue by zFernand0** [zowe/imperative#164]
Given that a property is marked `secure`, (e.g. username, password, ...), we need a way to prevent all components from writing said property to plain-text/visible places (e.g. log files, command responses, HTTP requests, etc.)

**Comment by AHumanFromCA** [comment]
One thing I want to clear up is this scenario:

Say the user installed a plugin that accidentally left in something like console.log(profile.secureField), do we expect the console output itself to be censored or do we not worry about this and say it is a bug with the plugin?

Also this exact same scenario could happen in a cli or imperative if a mistake is made.

The current behavior to this scenario would be that the log message would have profile.secureField in plaintext.

I'd also like to add a note about something I found out with Jenkins the other day. If I have this piece of code:

```groovy
withCredentials(usernameColonPassword(credentialsId: "blah", variable: "TOKEN")) {
  sh "git remote set-url --add origin https://\$TOKEN@github.com/some-repo.git"
  sh 'echo "PUSH INSIDE WITH CREDENTIALS" && git push --verbose'
}
sh 'echo "PUSH OUTSIDE WITH CREDENTIALS" && git push --verbose'
```

I will see something like this present in the output:

```
PUSH INSIDE WITH CREDENTIALS
...
push to repo https:/****@github.com/some-repo.git
...
PUSH OUTSIDE WITH CREDENTIALS
...
push to repo https://user:password@github.com/some-repo.git
```

This is very similar to the problem that we are talking about here as there are some scenarios that could allow the secure fields in Jenkins to be logged due to programmer error.

**Comment by ChrisBoehmCA** [comment]
This might be a complicated issue to tackle. By the time the user name and password are given to the rest client for example, the fact that they are marked "secure" is lost because it's no longer associated with the profile it was loaded from (if indeed it was loaded from a profile and not specified as a command line argument). We could just always censor the username and password of the session in the rest client, but if other fields such as hostname were marked secure in the futurewe wouldn't know that from the rest client. I'm thinking this will probably be multiple stories to implement

**Comment by zFernand0** [comment]
I don't believe we don't have any control over many programmer errors.
However, I do believe that this issue can be considered as completed when this was implemented
https://github.com/zowe/imperative/blob/17f5ee6720e1d780b7008150d87d98399611b0d1/packages/logger/src/LoggerUtils.ts#L168
