### ISSUE TITLE
IHandlerParameters.profiles IProfile members don't contain profile name

### ISSUE THREAD

**Issue by crshnburn** [zowe/imperative#176]
When an ICommandHandler gets the profiles from the IHandlerParameters object, the IProfile objects that are loaded do not have the name field populated so if there are issues with the profile the handler can't log the name of the profile that had an issue making it harder for the user to understand what has gone wrong.

```
{ type: 'zosconnect',
  address: 'http://xxxx:10113',
  required: null,
  user: undefined,
  password: undefined }
```
 
Shows the IProfile that is available for the [zosconnect](https://github.com/zosconnect/zowe-cli-zosconnect-plugin/blob/master/src/imperative.ts) profile.

**Comment by ChrisBoehmCA** [comment]
Hi, 

Sorry for the inconvenience. `name` and `type` was removed from the contents of profiles to allow `name` and `type` to be valid, non reserved fields on the profile. Maybe a new feature could be introduced to store the names of the loaded profiles somewhere.  So that it could be checked and logged. The log files probably contain the name of the profile that was loaded.

Since #34 was implemented, we recommend accessing the `arguments` on the command parameters instead of the profile, and adding an option for each profile field you have like user, password, address, host, and port. The `arguments` will automatically be filled in based on the user's profile, environmental variables, or command line options. 

See something like `zowe zos-jobs submit ds -h` under the z/OSMF connection options for an example
