### ISSUE TITLE
Always remove WebHelp's test runtime root directory

### ISSUE THREAD

**Issue by gejohnston** [zowe/imperative#272]
Within
```
imperative/__tests__/__integration__/cmd/__tests__/integration/cli/gen-help/Cmd.cli.gen-webhelp.example-test.integration.test.ts
```
ensure that
```
rimraf.sync(fakeRuntimeRootDir)
```
is always run, even when a previous "expect" clause fails.

**Comment by tjohnsonBCM** [comment]
Fixed in the lts-incremental branch in #294, but still needs to be fixed in the master branch.

The integration tests in the following file are missing a cleanup step in the master branch:
`__tests__\__integration__\cmd\__tests__\integration\cli\gen-help\Cmd.cli.gen-webhelp.example-test.integration.test.ts`

After the tests run, the "web-help" folder should be deleted, as is done in the lts-incremental branch:
```typescript
afterAll(async () => {
    // clean up webhelp files
    rimraf.sync("./__tests__/__integration__/cmd/lib/web-help");
});
```
