### ISSUE TITLE
README clarification - node-gyp

### ISSUE THREAD

**Issue by VitGottwald** [zowe/imperative#388]
Learning about imperative, I was reading README and the section about [build and install](https://github.com/zowe/imperative/blob/master/README.md#build-and-install-imperative-cli-framework-from-source) asks to install node-gyp. Is this really needed? I ran 

```sh
npm install && npm run build && npm run test
```

without any errors. I do NOT have node-gyp installed globally.

```sh
> npm -g ls --depth 0
/Users/vit/.fnm/node-versions/v12.16.1/installation/lib
├── npm@6.13.4
└── prettier@2.0.2
```

**Comment by tjohnsonBCM** [comment]
Imperative has 2 dev dependencies that use node-gyp:
* `keytar` - On install it runs `prebuild-install || node-gyp rebuild` ([source](https://github.com/atom/node-keytar/blob/master/package.json#L33)). If prebuilt native code exists for your OS and Node version, then the `prebuild-install` command will succeed and node-gyp isn't needed.
* `node-pty` - On install it runs node-gyp, but seems to not need it globally installed because it can fall back to using a version of node-gyp that is bundled with NPM:
`if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )`

I observed the same behavior as you on Windows, that Imperative installs successfully without node-gyp globally installed. That is because both of us are using a typical OS and Node version for which Keytar supplies prebuilt native code, so `prebuild-install` works and node-gyp isn't needed.

Keytar hasn't always bundled prebuilt native code (they didn't prior to version 5), hence why Imperative install used to fail if node-gyp was missing. Installing node-gyp is still required for some scenarios, for example if you are using non-LTS Node (13.x) which may not have prebuilt code bundled yet.

I think we have a few options:
* Continue recommending that all users globally install node-gyp before installing Imperative.
* Only recommend installing node-gyp for users with a non-LTS release of Node, assuming they are the only ones who need it.
* Provide an example of the install error resulting when node-gyp is missing, and inform users that if they encounter it the solution is to install node-gyp.

**Comment by zFernand0** [comment]
> * Provide an example of the install error resulting when node-gyp is missing, and inform users that if they encounter it the solution is to install node-gyp.

**Comment by VitGottwald** [comment]
Thank you @tjohnsonBCM for the detailed clarification. My thinking goes mainly to the _global_ install. If we need it, why not have it as a dev/dependency? Your second bullet seems to suggest that would work.
Then we would not have to mandate a separate command and touch global node_modules.

**Comment by tjohnsonBCM** [comment]
> Thank you @tjohnsonBCM for the detailed clarification. My thinking goes mainly to the _global_ install. If we need it, why not have it as a dev/dependency? Your second bullet seems to suggest that would work.
> Then we would not have to mandate a separate command and touch global node_modules.

node-gyp has prerequisites that can't be supplied by NPM, they require additional actions to be taken by the user, so it's not ideal to include it in package.json. On Windows for example, Visual Studio 2017 Build Tools and Python 3 must be installed. Because of this, the [node-gyp readme](https://github.com/nodejs/node-gyp#installation) recommends global installation so that a user can install it and perform the additional steps only once.

In my second bullet point, the reason why node-pty can work without users installing node-gyp is because the node-pty developers have chosen to support that scenario (where only a pre-installed version of node-gyp bundled with NPM is available). The keytar package does not detect node-gyp in this way, doing so would require its developers to change the keytar postinstall script.

**Comment by t1m0thyj** [comment]
We could remove the `node-gyp` dependency for most users if we switch to [`node-gyp-prebuilt-multiarch`](https://www.npmjs.com/package/node-pty-prebuilt-multiarch). It bundles prebuilt dependencies like Keytar does.

**Comment by t1m0thyj** [comment]
The node-pty dev dependency has been removed in the next branch, so node-gyp is no longer necessary and has been removed from the readme in #641
