### ISSUE TITLE
Explain unusual install command in README

### ISSUE THREAD

**Issue by VitGottwald** [zowe/imperative#390]
In the readme, there are several commands listed for the installation of imperative.

```sh
npm install --@zowe:registry=https://registry.npmjs.org --no-package-lock --force
npm install --save @zowe/imperative
```

this is quite unusual and I believe it deserves some elaboration why the user is asked to perform the installation this way.

Similarly for the lts version.

**Comment by zFernand0** [comment]
If I remember correctly, the reason behind this was because of the restrictive location where imperative was being published as part of the CI pipelines and the registry where the zowe scope was directed at was somewhat private. (Something called Giza Artifactory)

I believe this can be simplified to just `npm i --save @zowe/imeprative`, i.e. no need to force the users to go to the public registry if they already have an internal/enterprise registry where they get all other packages from.

**Comment by VitGottwald** [comment]
Thank you @zFernand0. If the instructions could be shortened to the standard command only that would be great!
