### ISSUE TITLE
Cannot read property 'callerLocation' of undefined

### ISSUE THREAD

**Issue by MarkAckert** [zowe/imperative#5]
From @dkelosky:
 
If you create a sample-cli and specify imperative configuration in your package.json like:
```json
    "imperative": {
        "configurationModule": "lib/wrongdir/imperative.js"
    },
```

where `wrongdir` is an invalid directory, you get an imperative initialization failure stating:
```
 { Error: An error was encountered attempting to load the specified configuration module. Cannot read property 'callerLocation' of undefined
```

`'callerLocation' of undefined` should probably not be the error message; rather, we should have a message like `configuration module not found`.

**Comment by mheuzey** [comment]
I was unable to recreate the problem, so perhaps the section of code throwing the error is being passed over by some changes within the past year and a half, but I believe I have located the issue. The message is being generated here
https://github.com/zowe/imperative/blob/4360ce5c1a20a4748d1d501fb73ca803eea42751/packages/imperative/src/Imperative.ts#L143-L148
because the callback `getCallerFile` is trying to throw a detailed error message
https://github.com/zowe/imperative/blob/4360ce5c1a20a4748d1d501fb73ca803eea42751/packages/utilities/src/ImperativeConfig.ts#L205-L211
when called within `ConfigurationLoader.load`, but it is using `this.callerLocation` instead of `ImperativeConfig.instance.callerLocation`.

Is anyone still able to create this problem, and can test the fix?
