### ISSUE TITLE
cannot [cli] config init in sub directory

### ISSUE THREAD

**Issue by dkelosky** [zowe/imperative#506]
If I run my CLI (zowe) init command like this:
`zowe config init`

Then I create a sub directory, called `test`.  I cannot init in that subdirectory:
`mkdir test && cd test && zowe config init`

This should be a permitted operation.

**Comment by gejohnston** [comment]
How does this fail ? - a command error ? - the config files are not created ? - the config files are wrong ?

In the branch next-refactor-config, I get the following results:

- Successfully run zowe config init
    - A zowe.config.json file is created with the expected template values
    - A zowe.schema.json file is created with lots of stuff
- Enter a child subdirectory and successfully run zowe config init again.
    - New config and schema files are created inside the subdirectory
- A diff shows that the two files in the parent directory are the same as the two files in the subdirectory

If this is the expected behavior, we should be able to close this issue when we merge the next-refactor-config branch into the next branch.

**Comment by t1m0thyj** [comment]
This sounds like expected behavior - @dkelosky can confirm 🙂 

I think the issue was that the config files weren't created in the subdirectory. So if `zowe config init` was already run in directory "A", then running `zowe config init` in subdirectory "A/B" wouldn't do anything.

**Comment by dkelosky** [comment]
At the time of writing, I think @t1m0thyj and myself both confirmed that running `zowe config init` in a sub directory didn't do anything, e.g. create a config.  

If that is no longer a problem, we can close this.
