### ISSUE TITLE
"zowe plugins validate" errors

### ISSUE THREAD

**Issue by Yuliya-Kirkorava** [zowe/imperative#858]
Hi,
I got errors when I run "zowe plugins validate" : 
![image](https://user-images.githubusercontent.com/96059205/181349957-960fad37-f836-4b4b-b567-3b0a7a134815.png)

![image](https://user-images.githubusercontent.com/96059205/181350644-fa0e3e5d-fa11-4914-b0d4-c37c2157ab2a.png)

![image](https://user-images.githubusercontent.com/96059205/181350153-5b21381f-8470-44ef-b418-26a460a8e43d.png)

What may be wrong here?

**Comment by t1m0thyj** [comment]
`@zowe/cli` and `@zowe/imperative` are not valid plug-ins for Zowe CLI.

`@zowe/cli` is the same package as Zowe CLI itself, and `@zowe/imperative` is an SDK used by the CLI that is already bundled with it.

To fix the validation errors you're receiving, the following commands should uninstall the invalid plug-ins without any loss of functionality:
```
zowe plugins uninstall @zowe/cli
zowe plugins uninstall @zowe/imperative
```

Then you can continue to use the CLI without plug-ins and hopefully without errors as well 🙂 If you would like to install Zowe CLI plug-ins, they follow the naming convention `X-for-zowe-cli` and there are a number available like the ones listed here: https://docs.zowe.org/stable/user-guide/cli-installplugins/#installing-plug-ins-from-an-online-registry

**Comment by Yuliya-Kirkorava** [comment]
Thanks for the quick respond! I have uninstalled both plugins and updated the code. Seems it works :) for me.

Do you know something about @zowe/zos-make-for-zowe-cli plugin? I see it's not compatible with Zowe V2. Are you going to update it?

**Comment by t1m0thyj** [comment]
The only `@zowe`-scoped plug-ins that are supported as part of the bundle on Zowe.org are the CICS, DB2, IMS, MQ, and z/OS FTP plug-ins (as well as Secure Credential Store but it's deprecated in Zowe v2 since it was migrated into the core CLI).

Other plug-ins like `@zowe/zos-make-for-zowe-cli` and `@zowe/tasks-for-zowe-cli` have been contributed by the community and receive less support. I don't have an ETA for when a `@zowe-v2-lts` tag will be released for those plug-ins, but in the meantime you could try their `@next` tag which is essentially a beta version containing changes for compatibility with Zowe v2.

**Comment by Yuliya-Kirkorava** [comment]
Thank you for information!
