### ISSUE TITLE
Add plugin post-install and pre-uninstall actions

### ISSUE THREAD

**Issue by adam-wolfe** [zowe/imperative#942]
Add post-install and pre-uninstall hooks to modify imperative.json to either specify a custom credential manager (upon credential manager plugin installation) or revert to the default Zowe CLI credential manager (upon credential manager plugin uninstallation).

**Comment by sosadchuk** [comment]
Hi, sorry for bringing this up - just wanted to know where it landed.

My guess this request was rejected due to work on the `secrets` component, however we could actually use some post-install hooks (wanted to display some intro lines of text with our samples repository link).

NPM's `postinstall` hook suport would work, it is suppressed upon using `zowe plugins install ...` at the moment.


Thanks,
Sergei.
